### ISSUE TITLE
First Video

### ISSUE THREAD

**Issue by 0x65-e** [LivingRoomFilmStudios/livingroomfilmstudios.github.io#4]
Wasn't our first video Dacia, not The Pearl? That _should_ be the first video, but The Pearl looks nicer.

**Comment by TrevorPeitzman** [comment]
True. I forgot about that one. I can change it if you want.

**Comment by 0x65-e** [comment]
I mean.... I don't know.

**Comment by TrevorPeitzman** [comment]
Will change then.

On Sat, Jan 30, 2016 at 5:04 PM, Faceless Hacker notifications@github.com
wrote:

> I mean.... I don't know.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LivingRoomFilmStudios/livingroomfilmstudios.github.io/issues/4#issuecomment-177352503
> .

## 

-_Trevor Peitzman_
SPL & Webmaster
(305) 563-4564
